name: FE and BE tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        with:
          start: npx cypress run --spec "cypress/integration/BE/**/*.js,cypress/integration/FE/**/*.js"
          record: false  # Do not record videos and screenshots
