name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run --spec "cypress/integration/BE/*.js" --spec "cypress/integration/FE/*.js"
          record: false
